test_that("multiplication works", {
  expect_equal(combination_count(5, 2), 10)
  expect_equal(combination_count(0, 0), 1)
  expect_equal(combination_count(10, 10), 1)
  expect_equal(combination_count(99, 0), 1)
  expect_equal(combination_count(30, 3), ncol(combn(30, 3)))
  expect_error(combination_count(3.5, 30), "input values must be whole numbers")
  expect_error(combination_count(3, 10.3), "input values must be whole numbers")
  expect_error(combination_count(-5, 2), "invalid input")
  expect_error(combination_count(10, -1), "invalid input")
  expect_error(combination_count(100, 101), "invalid input")
})
